In [1]:
import numpy as np

In [2]:
arr = np.array([2, 3, 4, 5, 10])
arr

array([ 2,  3,  4,  5, 10])

In [3]:
arr.dtype

dtype('int64')

In [4]:
arr - 2

array([0, 1, 2, 3, 8])

In [5]:
arr.sum()

np.int64(24)

In [6]:
sum(arr)

np.int64(24)

In [7]:
arr = np.array([2, 3, 4, 5, 10])
arr.size

5

In [8]:
arr.size, len(arr)

(5, 5)

In [10]:
arr.mean(), sum(arr) / len(arr)

(np.float64(4.8), np.float64(4.8))

In [11]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

# Generare numere random

In [19]:
np.random.random()

0.15042141937391806

In [26]:
np.random.randint(1, 10)

1

In [27]:
np.random.randint(1, 10, 3)

array([8, 9, 2])

In [28]:
np.random.randint(1, 10, 3)

array([3, 8, 1])

In [29]:
np.random.randint(1, 10, (3, 2))

array([[3, 5],
       [2, 5],
       [4, 2]])

In [30]:
np.random.randint(1, 10, (5, 4))

array([[7, 4, 9, 1],
       [6, 6, 5, 2],
       [6, 6, 5, 6],
       [2, 5, 4, 7],
       [1, 1, 8, 6]])

# Generare de numere consecutive

In [32]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [33]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np.array(range(10, 100))

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [36]:
np.arange(10, 100, dtype="float64")

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22.,
       23., 24., 25., 26., 27., 28., 29., 30., 31., 32., 33., 34., 35.,
       36., 37., 38., 39., 40., 41., 42., 43., 44., 45., 46., 47., 48.,
       49., 50., 51., 52., 53., 54., 55., 56., 57., 58., 59., 60., 61.,
       62., 63., 64., 65., 66., 67., 68., 69., 70., 71., 72., 73., 74.,
       75., 76., 77., 78., 79., 80., 81., 82., 83., 84., 85., 86., 87.,
       88., 89., 90., 91., 92., 93., 94., 95., 96., 97., 98., 99.])

In [39]:
arr = np.arange(1, 21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [41]:
arr.size # cate sunt in total

20

In [42]:
arr.shape

(20,)

In [43]:
arr.reshape((4, 5))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [44]:
arr.reshape((10, 2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [48]:
new_arr = arr.reshape((2, 10))
new_arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [49]:
new_arr.shape

(2, 10)

# 1. Operatii Matematice pe numpy 

In [50]:
new_arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [52]:
new_arr + 1 # operatie matematica

array([[ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21]])

In [53]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [54]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [55]:
new_arr.shape

(2, 10)

In [58]:
ones_arr = np.ones((2, 10))
ones_arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [57]:
new_arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [59]:
new_arr * ones_arr

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15., 16., 17., 18., 19., 20.]])

In [61]:
new_arr - ones_arr

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.]])

In [62]:
new_arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

# 2. Operatii logice pe numpy 

In [63]:
new_arr > 5

array([[False, False, False, False, False,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [64]:
new_arr % 3 == 0

array([[False, False,  True, False, False,  True, False, False,  True,
        False],
       [False,  True, False, False,  True, False, False,  True, False,
        False]])

In [65]:
new_arr[new_arr % 3 == 0]

array([ 3,  6,  9, 12, 15, 18])

In [66]:
new_arr[new_arr > 5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [67]:
new_arr[(new_arr % 3 == 0) & (new_arr > 5)]

array([ 6,  9, 12, 15, 18])

# 3. Citirea din numpy

In [68]:
new_arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [69]:
new_arr[1]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [70]:
new_arr[1][2]

np.int64(13)

In [71]:
new_arr[1, 2]

np.int64(13)

In [73]:
new_arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [74]:
new_arr[0, 0], new_arr[1, 0]

(np.int64(1), np.int64(11))

In [75]:
new_arr[0:2, 0]

array([ 1, 11])

In [76]:
new_arr[ : , 0]

array([ 1, 11])

In [77]:
new_arr[ : , -1]

array([10, 20])

# 4. Update in numpy

In [78]:
new_arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [80]:
new_arr[:,6]

array([ 7, 17])

In [81]:
new_arr[:,6] = 999
new_arr

array([[  1,   2,   3,   4,   5,   6, 999,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16, 999,  18,  19,  20]])

In [82]:
new_arr[0][1:6] = 333
new_arr

array([[  1, 333, 333, 333, 333, 333, 999,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16, 999,  18,  19,  20]])