In [2]:
import numpy as np

In [3]:
start_date = 1900
stop_date = 2100

In [6]:
all_years = np.arange(start_date, stop_date + 1)
all_years

array([1900, 1901, 1902, 1903, 1904, 1905, 1906, 1907, 1908, 1909, 1910,
       1911, 1912, 1913, 1914, 1915, 1916, 1917, 1918, 1919, 1920, 1921,
       1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932,
       1933, 1934, 1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943,
       1944, 1945, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954,
       1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965,
       1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976,
       1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987,
       1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998,
       1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009,
       2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020,
       2021, 2022, 2023, 2024, 2025, 2026, 2027, 2028, 2029, 2030, 2031,
       2032, 2033, 2034, 2035, 2036, 2037, 2038, 2039, 2040, 2041, 2042,
       2043, 2044, 2045, 2046, 2047, 2048, 2049, 20

# Varianta 1 - conditii

In [7]:
divizibil_cu_400 = all_years % 400 == 0
divizibil_cu_4  = all_years % 4 == 0
nedivizibil_cu_100 = all_years % 100 != 0

all_years[divizibil_cu_400 | (divizibil_cu_4 & nedivizibil_cu_100)]

array([1904, 1908, 1912, 1916, 1920, 1924, 1928, 1932, 1936, 1940, 1944,
       1948, 1952, 1956, 1960, 1964, 1968, 1972, 1976, 1980, 1984, 1988,
       1992, 1996, 2000, 2004, 2008, 2012, 2016, 2020, 2024, 2028, 2032,
       2036, 2040, 2044, 2048, 2052, 2056, 2060, 2064, 2068, 2072, 2076,
       2080, 2084, 2088, 2092, 2096])

In [8]:
all_years[(all_years % 400 == 0) | ((all_years % 4 == 0) & (all_years % 100 != 0))]

array([1904, 1908, 1912, 1916, 1920, 1924, 1928, 1932, 1936, 1940, 1944,
       1948, 1952, 1956, 1960, 1964, 1968, 1972, 1976, 1980, 1984, 1988,
       1992, 1996, 2000, 2004, 2008, 2012, 2016, 2020, 2024, 2028, 2032,
       2036, 2040, 2044, 2048, 2052, 2056, 2060, 2064, 2068, 2072, 2076,
       2080, 2084, 2088, 2092, 2096])

# Varianta 2 - cu adunarea array-urilor

In [10]:
divizibil_cu_400 = all_years % 400 == 0
years_400s = all_years[divizibil_cu_400]
years_400s

array([2000])

In [11]:
divizibil_cu_4  = all_years % 4 == 0
nedivizibil_cu_100 = all_years % 100 != 0

years_4_not_100s = all_years[divizibil_cu_4 & nedivizibil_cu_100]
years_4_not_100s

array([1904, 1908, 1912, 1916, 1920, 1924, 1928, 1932, 1936, 1940, 1944,
       1948, 1952, 1956, 1960, 1964, 1968, 1972, 1976, 1980, 1984, 1988,
       1992, 1996, 2004, 2008, 2012, 2016, 2020, 2024, 2028, 2032, 2036,
       2040, 2044, 2048, 2052, 2056, 2060, 2064, 2068, 2072, 2076, 2080,
       2084, 2088, 2092, 2096])

In [ ]:
print([1904, 1908, 1912, 1916, 1920, 1924, 1928, 1932, 1936, 1940, 1944,
       1948, 1952, 1956, 1960, 1964, 1968, 1972, 1976, 1980, 1984, 1988,
       1992, 1996, 2004, 2008, 2012, 2016, 2020, 2024, 2028, 2032, 2036,
       2040, 2044, 2048, 2052, 2056, 2060, 2064, 2068, 2072, 2076, 2080,
       2084, 2088, 2092, 2096] + [2000]) # concatenare de liste

[1904, 1908, 1912, 1916, 1920, 1924, 1928, 1932, 1936, 1940, 1944, 1948, 1952, 1956, 1960, 1964, 1968, 1972, 1976, 1980, 1984, 1988, 1992, 1996, 2004, 2008, 2012, 2016, 2020, 2024, 2028, 2032, 2036, 2040, 2044, 2048, 2052, 2056, 2060, 2064, 2068, 2072, 2076, 2080, 2084, 2088, 2092, 2096, 2000]


In [16]:
np.concat((years_400s, years_4_not_100s))

array([2000, 1904, 1908, 1912, 1916, 1920, 1924, 1928, 1932, 1936, 1940,
       1944, 1948, 1952, 1956, 1960, 1964, 1968, 1972, 1976, 1980, 1984,
       1988, 1992, 1996, 2004, 2008, 2012, 2016, 2020, 2024, 2028, 2032,
       2036, 2040, 2044, 2048, 2052, 2056, 2060, 2064, 2068, 2072, 2076,
       2080, 2084, 2088, 2092, 2096])

In [18]:
np.append(years_400s, years_4_not_100s)

array([2000, 1904, 1908, 1912, 1916, 1920, 1924, 1928, 1932, 1936, 1940,
       1944, 1948, 1952, 1956, 1960, 1964, 1968, 1972, 1976, 1980, 1984,
       1988, 1992, 1996, 2004, 2008, 2012, 2016, 2020, 2024, 2028, 2032,
       2036, 2040, 2044, 2048, 2052, 2056, 2060, 2064, 2068, 2072, 2076,
       2080, 2084, 2088, 2092, 2096])

In [21]:
years_4_not_100s + 2000

array([3904, 3908, 3912, 3916, 3920, 3924, 3928, 3932, 3936, 3940, 3944,
       3948, 3952, 3956, 3960, 3964, 3968, 3972, 3976, 3980, 3984, 3988,
       3992, 3996, 4004, 4008, 4012, 4016, 4020, 4024, 4028, 4032, 4036,
       4040, 4044, 4048, 4052, 4056, 4060, 4064, 4068, 4072, 4076, 4080,
       4084, 4088, 4092, 4096])