In [127]:
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt

In [128]:
BLACK = np.array([0, 0, 0])
YELLOW = np.array([255, 204, 0])
RED = np.array([221, 0, 0])

In [129]:
SCALE = 1 * 100

WIDTH = 15 * SCALE
HEIGHT = 9 * SCALE

In [130]:
WIDTH, HEIGHT = HEIGHT, WIDTH

In [131]:
steag_arr = np.ones((HEIGHT, WIDTH, 4), dtype=np.uint8)


In [132]:
steag_arr[:,:,-1] = 255
steag_arr

array([[[  1,   1,   1, 255],
        [  1,   1,   1, 255],
        [  1,   1,   1, 255],
        ...,
        [  1,   1,   1, 255],
        [  1,   1,   1, 255],
        [  1,   1,   1, 255]],

       [[  1,   1,   1, 255],
        [  1,   1,   1, 255],
        [  1,   1,   1, 255],
        ...,
        [  1,   1,   1, 255],
        [  1,   1,   1, 255],
        [  1,   1,   1, 255]],

       [[  1,   1,   1, 255],
        [  1,   1,   1, 255],
        [  1,   1,   1, 255],
        ...,
        [  1,   1,   1, 255],
        [  1,   1,   1, 255],
        [  1,   1,   1, 255]],

       ...,

       [[  1,   1,   1, 255],
        [  1,   1,   1, 255],
        [  1,   1,   1, 255],
        ...,
        [  1,   1,   1, 255],
        [  1,   1,   1, 255],
        [  1,   1,   1, 255]],

       [[  1,   1,   1, 255],
        [  1,   1,   1, 255],
        [  1,   1,   1, 255],
        ...,
        [  1,   1,   1, 255],
        [  1,   1,   1, 255],
        [  1,   1,   1, 255]],

       [[  1

In [133]:
new_image = Image.fromarray(steag_arr)
new_image.save("steag_negru.png")

In [134]:
steag_arr.shape

(1500, 900, 4)

In [135]:
WIDTH

900

In [136]:
WIDTH // 3 

300

In [137]:
steag_arr[:,0:WIDTH // 3, :3 ] = BLACK 

In [138]:
steag_arr[:, WIDTH // 3 : 2 * WIDTH // 3, :3 ] = RED 

In [139]:
steag_arr[:,  2 * WIDTH // 3 : , :3 ] = YELLOW

In [140]:
steag_arr.shape

(1500, 900, 4)

In [141]:
steag_arr.T.shape

(4, 900, 1500)

In [142]:
np.rot90(steag_arr, 1, (0,1)).shape

(900, 1500, 4)

In [143]:
steag_arr = np.rot90(steag_arr, 1, (1,0))

In [145]:
new_image = Image.fromarray(steag_arr)
new_image.save("steag_germania.png")

# Transpunerea unei matrici

In [147]:
arr = np.array([[1, 2], [3, 4]])
arr

array([[1, 2],
       [3, 4]])

In [148]:
arr.T

array([[1, 3],
       [2, 4]])