# pip install numpy

In [1]:
import numpy as np

In [2]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [4]:
arr = np.array([2, 3, 4, 5, 6])
arr

array([2, 3, 4, 5, 6])

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr = np.array([2, 3, 4, 5, 6.23])
arr

array([2.  , 3.  , 4.  , 5.  , 6.23])

In [ ]:
arr = np.array([2, 3, 4, 5, 6.23, "hello"])
arr

array(['2', '3', '4', '5', '6.23', 'hello'], dtype='<U32')

In [8]:
type(arr)

numpy.ndarray

In [9]:
arr.dtype

dtype('<U32')

In [10]:
arr = np.array([2, 3, 4, 5, 6])
arr, arr.dtype

(array([2, 3, 4, 5, 6]), dtype('int64'))

# tipuri de date in numpy

In [11]:
np.int8

numpy.int8

# uint8 - unsigned pe 8 bits de date : de la 0 pana la 255

In [15]:
arr = np.array([2, 3, 4, 5, 6, 255], dtype=np.uint8)

In [16]:
arr = np.array([2, 3, 4, 5, 6, 256], dtype=np.uint8)

OverflowError: Python integer 256 out of bounds for uint8

In [17]:
arr = np.array([2, 3, 4, 5, 6, 254], dtype=np.uint8)

In [18]:
arr = np.array([2, 3, 4, 5, 6, 254, -1], dtype=np.uint8)

OverflowError: Python integer -1 out of bounds for uint8

# int8 - signed (cu semn) pe 8 bits de date : de la -128 pana la 127

In [20]:
arr = np.array([2, 3, 4, 5, 6, 127, -128], dtype=np.int8)

In [21]:
arr = np.array([2, 3, 4, 5, 6, 128, -128], dtype=np.int8)

OverflowError: Python integer 128 out of bounds for int8

In [22]:
arr = np.array([2, 3, 4, 5, 6, 127, -129], dtype=np.int8)

OverflowError: Python integer -129 out of bounds for int8

# Fast mathematical operations over arrays

In [24]:
arr = np.array([10, 20, 30, 40, 50, 60])
arr

array([10, 20, 30, 40, 50, 60])

In [25]:
arr / 10

array([1., 2., 3., 4., 5., 6.])

In [26]:
arr = np.array([10, 20, 30, 40, 50, 60])
arr + 5

array([15, 25, 35, 45, 55, 65])

In [27]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([101, 202, 303, 404, 505, 606])

arr1 + arr2 

array([111, 222, 333, 444, 555, 666])

In [28]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([101, 202, 303, 404])

arr1 + arr2 

ValueError: operands could not be broadcast together with shapes (6,) (4,) 

In [30]:
arr = np.array([10, 20, 30, 40, 50, 60])
arr


array([10, 20, 30, 40, 50, 60])

In [31]:
arr % 3 == 0

array([False, False,  True, False, False,  True])

In [32]:
arr [ arr % 3 == 0]

array([30, 60])

In [33]:
arr = np.array([10, 20, 30, 40, 50, 60])

conditie = arr % 3 == 0
arr [ conditie]

array([30, 60])