In [1]:
import numpy as np

In [2]:

# %%
######### Exercitiul ################
# Creați un vector cu 10 elemente întregi, toate fiind egale cu 0.

np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
######### Exercitiul ################
# Creați un vector cu 10 elemente întregi, toate fiind egale cu 1.

np.ones(10)


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
# np.twos(10)

In [6]:
######### Exercitiul ################
# Creați un vector cu elemente întregi de la 0 la 9.

np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
######### Exercitiul ################
# Creați un vector cu elemente întregi de la 10 la 29.

np.arange(10, 30)


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [ ]:
######### Exercitiul ################
# Creați un vector cu elemente întregi de la 0 la 9 în ordine inversă.
np.arange(9, -1, -1)


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [14]:
np.arange(0, 10)[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [16]:
######### Exercitiul ################
# Creați un vector cu 10 elemente aleatoare între 0 și 1.

np.random.random(10)

array([0.21377195, 0.61896428, 0.65320868, 0.15372457, 0.29623707,
       0.85576557, 0.78420089, 0.59717774, 0.11644739, 0.98047085])

In [19]:
######### Exercitiul ################
# Creați o matrice 3x3 cu elemente întregi aleatoare între 0 și 9.
np.arange(9).reshape(3, 3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [20]:
######### Exercitiul ################
# Creați o matrice identitate 5x5.
np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [22]:
np.identity(5, dtype=np.int8)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int8)

In [23]:
np.eye(5, dtype=np.int8)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int8)

In [25]:

matrix = np.zeros((5, 5))
for i in range(5):
    matrix[i, i] = 1
matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
######### Exercitiul ################
# Adunați două matrici de dimensiuni egale (de exemplu, 3x3).

np.zeros((3, 3)) + np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [27]:
######### Exercitiul ################
# Înmulțiți două matrici de dimensiuni corespunzătoare (de  exemplu, 2x3 și 3x2).

m1 = np.random.randint(1, 5, (2, 3))
m2  = np.random.randint(1, 5, (3, 2))
print("m1=", m1)
print("m2=", m2)


m1= [[2 4 4]
 [3 1 2]]
m2= [[1 2]
 [2 1]
 [3 2]]


In [29]:
np.matmul(m1, m2)

array([[22, 16],
       [11, 11]])

In [30]:
np.matmul(m2, m1)

array([[ 8,  6,  8],
       [ 7,  9, 10],
       [12, 14, 16]])

In [31]:
######### Exercitiul ################
# Transpuneți o matrice (de exemplu, 3x4).

m = np.random.randint(1, 5, (3, 4))
print(m)

[[1 4 2 2]
 [2 1 3 1]
 [4 1 2 1]]


In [32]:
m.T

array([[1, 2, 4],
       [4, 1, 1],
       [2, 3, 2],
       [2, 1, 1]])

In [33]:
######### Exercitiul ################
# Găsiți valoarea maximă dintr-un vector.

m.max()

np.int64(4)

In [34]:
######### Exercitiul ################
# Găsiți indicele valorii maxime dintr-un vector.

m.argmax()

np.int64(1)

In [35]:
######### Exercitiul ################
# Găsiți media aritmetică a valorilor dintr-o matrice.
m.mean()

np.float64(2.0)